abz_agency/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('employee.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/urls.py
from django.conf.urls import url
#from .views import Index
from . import views

urlpatterns = [
    url(r'^$', views.show_employees, name='show_employees'),
    url(r'^employees$', views.show_employees, name='show_employees'),
    url(r'^change_boss/$', views.change_boss, name='change_boss'),
    url(r'^employees_all/$', views.show_employees_all, name='show_employees_all'),
    url(r'^edit/(?P<id>\d+)/', views.edit, name='edit'),
    url(r'^delete/(?P<id>\d+)/', views.delete, name='delete'),
]

users/urls.py
from django.conf.urls import url

from . import views


app_name = 'users'

urlpatterns = [
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

employee/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.

class Employee(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    employment_position = models.CharField(max_length=200)
    employment_start_date = models.DateTimeField(auto_now_add=False)
    salary = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    employment_photo = models.ImageField(blank=True, upload_to='images/%Y/%m/%d', help_text='150x150px', verbose_name='employment_photo')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    def __str__(self):
        return str(self.id) + ' Name: ' + self.name

    class MPTTMeta:
        order_insertion_by = ['name']

users/models.py
from django.db import models

# Create your models here.

employee/forms.py
from django import forms

from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'employment_position', 'employment_start_date', 'salary', 'employment_photo', 'parent']

employee/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Employee
from .forms import EmployeeForm
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.db.models import Q



# Create your views here.

def show_employees(request):
    global employees
    if request.is_ajax():
        text = request.GET['children_id']
        node = Employee.objects.get(id=text)
        employees = node.get_descendants(include_self = "True").filter(level__lte=node.level + 3)
        data = {}
        data['employees'] = employees
        response = render(request, 'employees_list.html', {'employees': employees})
        return response
    else:
        employees = Employee.objects.all().filter(level__lte=1)
        return render(request, "employees.html", {'employees': employees})

def change_boss(request):
    if request.is_ajax():
        boss_id = request.GET['boss_id']
        children_id = request.GET['children_id']
        if boss_id == "nestable":
            current_child = Employee.objects.get(id=children_id)
            current_child.move_to(None, 'first-child')
            current_child.save()
        else:
            parent = Employee.objects.get(id=boss_id)
            current_child = Employee.objects.get(id=children_id)
            current_child.move_to(parent, 'first-child')
            current_child.save()
        return HttpResponse('')

def show_employees_all(request):
    if request.user.is_authenticated:
        if request.is_ajax():
            sort_by = request.GET['sort_by']
            search_text = request.GET['q_search']
            employees = Employee.objects.order_by(sort_by).filter(Q(employment_position__icontains=search_text))
            employees = employees | Employee.objects.order_by(sort_by).filter(Q(name__icontains=search_text))
            employees = employees | Employee.objects.order_by(sort_by).filter(Q(salary__icontains=search_text))
            employees = employees | Employee.objects.order_by(sort_by).filter(Q(employment_start_date__icontains=search_text))
            context = {}
            current_page = Paginator(list(employees), 20)
            page = request.GET['page']
            try:
                context['employees'] = current_page.page(page)
            except PageNotAnInteger:
                context['employees'] = current_page.page(1)
            except EmptyPage:
                context['employees'] = current_page.page(current_page.num_pages)
            response = render(request, 'employees_all_sort.html', context)
            return response
        else:
            employees = Employee.objects.order_by('date_added')
            context = {}
            current_page = Paginator(list(employees), 20)
            page = request.GET.get('page')
            try:
                context['employees'] = current_page.page(page)
            except PageNotAnInteger:
                context['employees'] = current_page.page(1)
            except EmptyPage:
                context['employees'] = current_page.page(current_page.num_pages)
            return render(request, 'employees_all.html', context)
    else:
        return HttpResponseRedirect("/users/login")

def edit (request, id):
    employee = Employee.objects.get(id=id)
    if request.method != 'POST':
        form = EmployeeForm(instance=employee, prefix='form')
        request.session['return_path'] = request.META.get('HTTP_REFERER','/')
    else:
        form = EmployeeForm(request.POST, instance=employee, prefix='form')
        if form.is_valid():
            employee = form.save(commit=False)
            employee.save()
        return HttpResponseRedirect(request.session['return_path'])
    context = {'form': form}
    return render(request, 'edit.html', context)

def delete (request, id):
    parent = Employee.objects.get(id=id)
    for child in parent.get_children():
        print(child)
        child.parent = parent.parent
        child.save()
    parent.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

users/views.py
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login


from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.contrib.auth import logout
# Create your views here.


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/employees"
    template_name = "register.html"
    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)



class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = "/employees"
    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)



class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/employees")

employee/templates/edit.html
<form method='post' enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" class="submit" value="Upload"></p>
</form>

employee/templates/employees.html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <title>jQuery Nestable Plugin Examples</title>
    <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <style type="text/css">


.cf:after { visibility: hidden; display: block; font-size: 0; content: " "; clear: both; height: 0; }
* html .cf { zoom: 1; }
*:first-child+html .cf { zoom: 1; }

html { margin: 0; padding: 0; }
body { font-size: 100%; margin: 0; font-family: 'Helvetica Neue', Arial, sans-serif; }

h1 { font-size: 1.75em; margin: 0 0 0.6em 0; }

a { color: #2996cc; }
a:hover { text-decoration: none; }

p { line-height: 1.5em; }
.small { color: #666; font-size: 0.875em; }
.large { font-size: 1.25em; }

/**
 * Nestable
 */

.dd { position: relative; display: block; margin: 0; padding: 0; max-width: 800px; list-style: none; font-size: 13px; line-height: 20px; margin-left: auto; margin-right: auto; }

.dd-list { display: block; position: relative; margin: 0; padding: 0; list-style: none; }
.dd-list .dd-list { padding-left: 30px; }
.dd-collapsed .dd-list { display: none; }

.dd-item,
.dd-empty,
.dd-placeholder { display: block; position: relative; margin: 0; padding: 0; min-height: 20px; font-size: 13px; line-height: 20px; }

.dd-handle { display: block; height: 30px; margin: 5px 0; padding: 5px 10px; color: #333; text-decoration: none; font-weight: bold; border: 1px solid #ccc;
    background: #fafafa;
    background: -webkit-linear-gradient(top, #fafafa 0%, #eee 100%);
    background:    -moz-linear-gradient(top, #fafafa 0%, #eee 100%);
    background:         linear-gradient(top, #fafafa 0%, #eee 100%);
    -webkit-border-radius: 3px;
            border-radius: 3px;
    box-sizing: border-box; -moz-box-sizing: border-box;
}
.dd-handle:hover { color: #2ea8e5; background: #fff; }

.dd-item > button { display: block; position: relative; cursor: pointer; float: left; width: 25px; height: 20px; margin: 5px 0; padding: 0; text-indent: 100%; white-space: nowrap; overflow: hidden; border: 0; background: transparent; font-size: 12px; line-height: 1; text-align: center; font-weight: bold; }
.dd-item > button:before { content: '+'; display: block; position: absolute; width: 100%; text-align: center; text-indent: 0; }
.dd-item > button[data-action="collapse"]:before { content: '-'; }

.dd-placeholder,
.dd-empty { margin: 5px 0; padding: 0; min-height: 30px; background: #f2fbff; border: 1px dashed #b6bcbf; box-sizing: border-box; -moz-box-sizing: border-box; }
.dd-empty { border: 1px dashed #bbb; min-height: 100px; background-color: #e5e5e5;
    background-image: -webkit-linear-gradient(45deg, #fff 25%, transparent 25%, transparent 75%, #fff 75%, #fff),
                      -webkit-linear-gradient(45deg, #fff 25%, transparent 25%, transparent 75%, #fff 75%, #fff);
    background-image:    -moz-linear-gradient(45deg, #fff 25%, transparent 25%, transparent 75%, #fff 75%, #fff),
                         -moz-linear-gradient(45deg, #fff 25%, transparent 25%, transparent 75%, #fff 75%, #fff);
    background-image:         linear-gradient(45deg, #fff 25%, transparent 25%, transparent 75%, #fff 75%, #fff),
                              linear-gradient(45deg, #fff 25%, transparent 25%, transparent 75%, #fff 75%, #fff);
    background-size: 60px 60px;
    background-position: 0 0, 30px 30px;
}

.dd-dragel { position: absolute; pointer-events: none; z-index: 9999; }
.dd-dragel > .dd-item .dd-handle { margin-top: 0; }
.dd-dragel .dd-handle {
    -webkit-box-shadow: 2px 4px 6px 0 rgba(0,0,0,.1);
            box-shadow: 2px 4px 6px 0 rgba(0,0,0,.1);
}

/**
 * Nestable Extras
 */

.nestable-lists { display: block; clear: both; padding: 30px 0; width: 100%; border: 0; border-top: 2px solid #ddd; border-bottom: 2px solid #ddd; }

#nestable-menu { padding: 0; margin: 20px 0; }

#nestable-output,

@media only screen and (min-width: 700px) {

    .dd { float: left; width: 48%; }
    .dd + .dd { margin-left: 2%; }

}

.dd-hover > .dd-handle { background: #2ea8e5 !important; }

/**
 * Nestable Draggable Handles
 */

*{
  box-sizing: border-box;
}
.d-table{
  display: table;
  width: 100%;
  border-collapse: collapse;
}
.d-tr{
  display: table-row;
}
.d-td{
  display: table-cell;
  text-align: center;
  border: none;
  border: 1px solid #ccc;
  vertical-align: middle;
}
.d-td:not(.no-p){
  padding: 4px;
}


    </style>
</head>
<body>

{% load staticfiles %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="{% static 'js/jquery.nestable.js' %}"></script>


<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card card-image" style="border: none;">
    <div class="rgba-black-strong py-5 px-4">
      <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-xl-8">
          <div class="card mb-4">
            <div class="card-header p-0 z-depth-1">
              <div class="d-table">
                <div class="d-tr">
                  <div class="d-td" style="width:60%">
                    <i class="fa fa-cloud fa-2x p-3 mr-4 float-left black-text" aria-hidden="true"></i>
                    <h4 class="text-uppercase white-text mb-0 py-3 mt-1">
                        {% if user.is_authenticated %}
                            <a href="{% url 'show_employees_all' %}">employee hierarchy</a>
                        {% else %}
                            employee hierarchy
                        {% endif %}
                    </h4>
                  </div>
                  <div class="d-td" style="width:20%">
                      {% if user.is_authenticated %}
                        <h4>HI, {{ user }}</h4>
                      {% else %}
                        <a href="{% url 'users:register' %}"><h4>REGISTRATION</h4></a>
                      {% endif %}
                  </div>
                  <div class="d-td" style="width:20%">
                      {% if user.is_authenticated %}
                        <a href="{% url 'users:logout' %}"><h4>LOG OUT</h4></a>
                      {% else %}
                        <a href="{% url 'users:login' %}"><h4>LOG IN</h4></a>
                      {% endif %}
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>





{% csrf_token %}

{% load mptt_tags %}


<div class="cf nestable-lists">
  <div class="dd" id="nestable">
    <ol class="root dd-list">
      {% recursetree employees %}
        <li class="dd-item" id="{{ node.id }}">
          <div class="dd-handle" id="div{{ node.id }}">{{ node.name }}, Position - {{ node.employment_position }}, Salary - {{ node.salary }}</div>
          {% if not node.is_leaf_node %}
            <ol class="children">
                {{ children }}
            </ol>
          {% endif %}
        </li>
      {% endrecursetree %}
    </ol>
  </div>
</div>











<script>
        function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
</script>



<script>


$(document).ready(function()
{
    $("button").click(function(){
        $("#div1").load("employees_list.txt");
    });
    // activate Nestable for list 1
    $('#nestable').nestable({
        group: 1
    })//.nestable('collapseAll');
    $('#nestable2').nestable({
        group: 1
    })
    .on('change', updateOutput);



    $('#nestable-menu').on('click', function(e)
    {
        var target = $(e.target),
            action = target.data('action');
        if (action === 'collapse-all') {
            $('.dd').nestable('collapseAll');
        }
        if (action === 'expand-all') {
            $('.dd').nestable('expandAll');
        }
    });
});


$('.dd').on('uploadchildren', function() {

});

</script>
  </body>
</html>

employee/templates/employees_all.html
<head>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">


<!------ Include the above in your HEAD tag ---------->

{% load static %}

<link rel="stylesheet" href="/static/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
<script type="text/javascript" src="/static/fancybox/jquery.fancybox.pack.js"></script>
<script type="text/javascript" src="/static/fancybox/script.js"></script>
<link rel="stylesheet" type="text/css" href="/static/fancybox/style.css">

<style>


.fancybox {
    vertical-align: middle;
    width: 35px;
    height: 35px;
    border-radius: 50%;
}



*{
  box-sizing: border-box;
}
.d-table{
  display: table;
  width: 100%;
  border-collapse: collapse;
}
.d-tr{
  display: table-row;
}
.d-td{
  display: table-cell;
  text-align: center;
  border: none;
  border: 1px solid #ccc;
  vertical-align: middle;
}
.d-td:not(.no-p){
  padding: 4px;
}



.img_wrapper.loaded img{
    opacity: 1;
}

    input.example {
        padding: 8.5px;
        font-size: 17px;
        border: 1px solid grey;
        float: left;
        width: 100%;
        background: #f1f1f1;
    }

  form.example button {
      float: left;
      width: 20%;
      padding: 10px;
      background: #f43f3f;
      color: white;
      font-size: 17px;
      border: 1px solid grey;
      border-left: none;
      cursor: pointer;
  }

  form.example button:hover {
      background: #700a0a;
  }

  form.example::after {
      content: "";
      clear: both;
      display: table;
  }
  a.previous {
      background-color: #FFFFFF;
      color: black;
      margin: 10px;
  }

  a.next {
      background-color: #FFFFFF;
      color: black;
      margin: 10px;
  }

  a.current {
      color: black;
      margin: 10px;
  }

  a.round {
      border-radius: 50%;
      margin: 10px;
  }

  a.link_post:hover {
    background-color: #FFFFFF;
    color: black;
    margin: 10px;
  }

</style>

</head>




<body>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card card-image" style="border: none;">
    <div class="rgba-black-strong py-5 px-4">
      <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-xl-8">
          <div class="card mb-4">
            <div class="card-header p-0 z-depth-1">
              <div class="d-table">
                <div class="d-tr">
                  <div class="d-td" style="width:60%">
                    <i class="fa fa-cloud fa-2x p-3 mr-4 float-left black-text" aria-hidden="true"></i>
                    <h4 class="text-uppercase white-text mb-0 py-3 mt-1">
                        {% if user.is_authenticated %}
                            <a href="{% url 'show_employees' %}">employee hierarchy</a>
                        {% else %}
                            employee hierarchy
                        {% endif %}
                    </h4>
                  </div>
                  <div class="d-td" style="width:20%">
                      {% if user.is_authenticated %}
                        <h4>HI, {{ user }}</h4>
                      {% else %}
                        <a href="{% url 'users:register' %}"><h4>REGISTRATION</h4></a>
                      {% endif %}
                  </div>
                  <div class="d-td" style="width:20%">
                      {% if user.is_authenticated %}
                        <a href="{% url 'users:logout' %}"><h4>LOG OUT</h4></a>
                      {% else %}
                        <a href="{% url 'users:login' %}"><h4>LOG IN</h4></a>
                      {% endif %}
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




<div class="rgba-black-strong py-5 px-4">
<input id="searchTxt" placeholder="add your text here..." class="example"></input>
</div>



<div class="rgba-black-strong py-5 px-4">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-xl-8">
            <div class="card-header p-0 z-depth-1">
                <div class="d-table">
                    <div class="d-tr">
                        <div class="d-td" style="width:35%" onclick="search_text('name')"><h4>EMPLOYEE NAME</h4></div>
                        <div class="d-td" style="width:15%" onclick="search_text('employment_position')"><h4>POSITION</h4></div>
                        <div class="d-td" style="width:15%" onclick="search_text('employment_start_date')"><h4>START DATE</h4></div>
                        <div class="d-td" style="width:15%" onclick="search_text('salary')"><h4>SALARY</h4></div>
                        <div class="d-td" style="width:10%"><h4>PHOTO</h4></div>
                        <div class="d-td" style="width:10%"><h4>DELETE</h4></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% block page %}
<div id="div_sort">
{% include 'employees_all_sort.html' %}
</div>
{% endblock %}






<script>window.jQuery || document.write('<script src="path/to/your/jquery"><\/script>')</script>
<script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>


<script>
var page_num = 1;
var sort_text = 'date_added';
var search_text_all = '';
window.onkeyup = keyup;

function num_up() {
    page_num = page_num + 1;
    sort();
};

function num_down() {
    page_num = page_num - 1;
    sort();
};

function search_text(i) {
    if (i === undefined) {
        sort_text = 'date_added';
    } else {
        sort_text = i;
    }
    sort();
};

function keyup(e) {
    search_text_all = e.target.value;
    sort();
};

function sort() {
    $.ajax(
    {
        type:"GET",
        url:"/employees_all",
        data:{sort_by: sort_text,
            page: page_num,
            q_search: search_text_all,
        },

        success : function (data) {
            $("#div_sort").replaceWith(data);
        }
    })
};
</script>


</body>

employee/templates/employees_all_sort.html
<div id="div_sort">

    <div class="rgba-black-strong py-0 px-4">
      <div class="row d-flex justify-content-center">
        <div class="col-md-10 col-xl-8">
          <div class="card mb-4">
            <div class="card-header p-0 z-depth-1">
                <div class="d-table"><div id="div_sort">
                    {% for employee in employees %}
                        <div class="d-table">
                            <div class="d-tr">
                                <div class="d-td" style="width:35%"><h4><a href="{% url 'edit' id=employee.id %}">{{ employee.name }}</a></h4></div>
                                <div class="d-td" style="width:15%"><h4>{{ employee.employment_position }}</h4></div>
                                <div class="d-td" style="width:15%"><h4>{{ employee.employment_start_date|date:'Y.M.d' }}</h4></div>
                                <div class="d-td" style="width:15%"><h4>{{ employee.salary }}</h4></div>
                                <div class="d-td" style="width:10%"><img src={{ employee.employment_photo.url }} alt="Avatar" class="fancybox" rel="{{ employee.name }}" href="{{ employee.employment_photo.url }}" onload="imgLoaded(this)"/></div>
                                <div class="d-td" style="width:10%"><a href="{% url 'delete' id=employee.id %}"><h4>DELETE</h4></a></div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>








<div class="pagination" style="text-align: center; font-size: 20px">
    <div class="d-td" style="width:100%">
    {% with employees.paginator.num_pages as num_pages %}

    {% if employees.has_previous %}
        <div class="previous" onclick="num_down()">&laquo; Previos</div>
    {% endif %}

    {% for num in employees.paginator.page_range %}
        {% if employees.number|add:'-3' == num %}
          {# First page #}
            <a href="?page=1">1</a>
            {% if num != 1 %}
              <a>&#8943;</a>
            {% endif %}
        {% elif num == employees.number %}
          {# Current page #}
              <span class="current"><b>{{ num }}</b></span>
        {% elif employees.number|add:'-3' < num and num < employees.number|add:'3' %}
          {# Pages around current page #}
              {{ num }}
        {% elif employees.number|add:'3' == num %}
          {# Last page #}
              {% if num != num_pages %}
                  <a>&#8943;</a>
              {% endif %}
              {{ num_pages }}
          {% endif %}
        {% endfor %}

      {% if employees.has_next %}
          <div class="next" onclick="num_up()">Next &raquo</div>
      {% endif %}

    {% endwith %}
    </div>
</div>

</div>

employee/templates/employees_list.html
{% load mptt_tags %}
  {% recursetree employees %}
    <li class="dd-item" id="{{ node.id }}">
        <div class="dd-handle" id="div{{ node.id }}">{{ node.name }}, Position - {{ node.employment_position }}, Salary - {{ node.salary }}</div>
          {% if not node.is_leaf_node %}
            <ol class="children">
                {{ children }}
            </ol>
          {% endif %}
    </li>
  {% endrecursetree %}

users/templates/login.html
<html>
  <head>
    <title>Регистрация</title>
  </head>

  <body>
        <form action="" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="button">Вход</button>
        </form>
  </body>
</html>

users/templates/register.html
<html>
  <head>
    <title>Регистрация</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Зарегистрироваться</button>
    </form>
  </body>
</html>